### ISSUE TITLE
App crashes when rotated to vertical.

### ISSUE THREAD

**Issue by slogan621** [slogan621/tscharts-station#5]
App crashes when rotated to vertical. Update thread is executing when dependent activity has been destroyed.

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.thousandsmiles.thousandsmilesstation, PID: 19998
                  java.lang.IllegalStateException: Activity has been destroyed
                      at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1864)
                      at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
                      at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:614)
                      at org.thousandsmiles.thousandsmilesstation.StationActivity.updatePatientDetail(StationActivity.java:355)
                      at org.thousandsmiles.thousandsmilesstation.StationActivity.access$300(StationActivity.java:48)
                      at org.thousandsmiles.thousandsmilesstation.StationActivity$UpdatePatientLists$2.run(StationActivity.java:101)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5491)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
I/AndroidRuntime: To Report FATAL to activityManagerService
I/AndroidRuntime: Finished reporting FATAL to activityManagerService
I/Process: Sending signal. PID: 19998 SIG: 9
Disconnected from the target VM, address: 'localhost:8615', transport: 'socket'

**Comment by slogan621** [comment]
Fix will be to force activities to landscape in the manifest.
